version: '3.8'
networks:
  app-network:
    driver: bridge

services:
  db:
    image: postgres:13.9-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: trades
    ports:
      - "5432:5432"
    networks:
      - app-network

  trade_service:
    build: ./trade_service
    ports:
      - "5001:5001"
    depends_on:
      - db
    restart: on-failure
    networks:
      - app-network

  portfolio_service:
    build: ./portfolio_service
    ports:
      - "5002:5002"
    depends_on:
      - db
    restart: on-failure
    networks:
      - app-network

  frontend:
    image: nginx:alpine
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Mount nginx.conf at the correct path
    ports:
      - "80:80"
    depends_on:
      - trade_service
      - portfolio_service
    networks:
      - app-network  # Make sure this network matches others
    restart: on-failure

  # AWS X-Ray Daemon
  xray-daemon:
    image: amazon/aws-xray-daemon
    environment:
      - AWS_ACCESS_KEY_ID=dummy_key_id
      - AWS_SECRET_ACCESS_KEY=dummy_secret_key
      - AWS_REGION=${AWS_REGION:-ap-southeast-1}
    ports:
      - "2000:2000/udp"
      - "2000:2000/tcp"
    command: ["--local-mode", "--bind=0.0.0.0:2000", "--log-level=debug"]
    restart: on-failure

  # OpenTelemetry Collector
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.70.0
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    command: ["--config=/etc/otel-collector-config.yaml"]
    environment:
      - AWS_ACCESS_KEY_ID=dummy_key_id
      - AWS_SECRET_ACCESS_KEY=dummy_secret_key
      - AWS_REGION=${AWS_REGION:-ap-southeast-1}
    ports:
      - "4317:4317"  # OTLP gRPC
      - "4318:4318"  # OTLP HTTP
      - "8889:8889"  # Prometheus metrics
    depends_on:
      - xray-daemon
    restart: on-failure
