# otel-collector-config.yaml
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
  
  resource:
    attributes:
      - key: deployment.environment
        value: production
        action: upsert
      - key: service.namespace
        value: trading-app
        action: upsert

exporters:
  awsxray:
    region: "${AWS_REGION}"
    local_mode: true
    endpoint: "http://xray-daemon:2000"
    # Remove the invalid keys (aws_log_level, tracing_sdk_version)
    
  logging:
    verbosity: detailed
  
  awscloudwatchlogs:
    region: "${AWS_REGION}"
    log_group_name: "/trading-app/services"
    log_stream_name: "otel-collector"
    
  # Add prometheus exporter for metrics
  prometheus:
    endpoint: "0.0.0.0:8889"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, resource]
      exporters: [awsxray, logging]
    
    logs:
      receivers: [otlp]
      processors: [batch, resource]
      exporters: [awscloudwatchlogs, logging]
      
    # Add metrics pipeline
    metrics:
      receivers: [otlp]
      processors: [batch, resource]
      exporters: [prometheus, logging]
  
  telemetry:
    logs:
      level: info