# otel-collector-config.yaml
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
  
  resource:
    attributes:
      - key: deployment.environment
        value: production
        action: upsert
      - key: service.namespace
        value: trading-app
        action: upsert

exporters:
  awsxray:
    region: "${AWS_REGION}"
    local_mode: true
    endpoint: "http://xray-daemon:2000"
    
  logging:
    verbosity: detailed
    
  # Remove the awscloudwatchlogs exporter which is causing authentication issues
  
  prometheus:
    endpoint: "0.0.0.0:8889"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, resource]
      exporters: [awsxray, logging]
      
    # Update logs pipeline to use only logging exporter
    logs:
      receivers: [otlp]
      processors: [batch, resource]
      exporters: [logging]
    
    metrics:
      receivers: [otlp]
      processors: [batch, resource]
      exporters: [prometheus, logging]
  
  telemetry:
    logs:
      level: info