version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: trades
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d trades"]
      interval: 10s
      timeout: 5s
      retries: 5

  trade_service:
    build: ./trade_service
    ports:
      - "5001:5001"
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
      - PORT=5001
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: on-failure

  portfolio_service:
    build: ./portfolio_service
    ports:
      - "5002:5002"
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
      - PORT=5002
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5002/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: on-failure

  frontend:
    image: nginx:alpine
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      trade_service:
        condition: service_healthy
      portfolio_service:
        condition: service_healthy
